### ISSUE TITLE
The banner notification shows up in the print rendering of a record page

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1988]
[print-issues-2020-07-28.pdf](https://github.com/informatics-isi-edu/chaise/files/4991783/print-issues-2020-07-28.pdf)

Notice at the top of the 1st page the notification banner:

> Success Your data has been submitted. Showing you the result set...

I think that should be excluded from the print.css.

I imagine that an error banner would have also shown up in a print out but I did not test for that.

**Comment by DamCousik** [comment]
This has been fixed. Please test the same in FaceBase -  @robes

**Comment by robes** [comment]
Still happens on facebase. I just went to a record, added a related record, returned to the original record, printed => open as PDF and the “Success…” banner is in the print out.

**Comment by RFSH** [comment]
@robes She fixed this in a PR. So you're right. It still is not properly working on facebase (or any other deployments for that matter).

@DamCousik Please make the announcements after the change is merged with master. In general, you should wait for the hourly update to take place after your merge, test it yourself to make sure it's properly fixed, and then ask someone (usually the original writer of the issue) to verify the fix.

**Comment by robes** [comment]
ok. thanks for the clarification.

**Comment by DamCousik** [comment]
@RFSH Sure, will do once it is merged.

**Comment by DamCousik** [comment]
@robes , the changes were merged. It should reflect now. Please test it and let me know if there are any issues

**Comment by robes** [comment]
I just reproduced the bug on dev facebase @11:15AM. Can you please work with @Alejandro Bugacov<mailto:bugacov@isi.edu> / @bugacov to confirm that this is fixed? Thanks, Rob


On 8/10/20, 9:18 AM, "Damini Cousik" <notifications@github.com<mailto:notifications@github.com>> wrote:


@robes<https://github.com/robes> , the changes were merged. It should reflect now. Please test it and let me know if there are any issues

**Comment by DamCousik** [comment]
@robes sorry for the last update, turns out I had closed the PR without merging the changes. My bad. I merged the changes and tested it again on FaceBase and it works for me (https://dev.facebase.org/chaise/record/#1/isa:data_access_request/RID=1-KREY). Kindly check if it is working for you as well after which I will close the ticket.
Apologies for the back and forth.

**Comment by robes** [comment]
thanks. i can confirm the fix on the dev fb server.
