### ISSUE TITLE
repeated table/column name in request leading to self-link error 

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#478]

**Comment by svoinea** [comment]
Fixed in commit 6264728132ba6fbda69ebb39f785f435020f304c
The query predicate excludes now the main table to join with itself.
Ready for review.

**Comment by akumar03** [comment]
I still see the issue in GPCR when I go to the following url: https://dev.gpcrconsortium.org/chaise/search/#1/gpcr_browser:construct_gui?facets=(construct_gui:site::eq::USC)&layout=table&page=1

Here is the error log:
ERROR: 409
ResponseText: 409 Conflict
The request conflicts with the state of the server. Table name construct_deletion is ambiguous.
TextStatus: error
ErrorThrown: Conflict
URL: https://dev.gpcrconsortium.org/ermrest/catalog/1/aggregate/A:=gpcr_browser:construct_gui/$A/A2:=construct_deletion/$A/$A2/min_deletion_start_position:=min(deletion_start_position),max_deletion_start_position:=max(deletion_start_position),min_deletion_end_position:=min(deletion_end_position),max_deletion_end_position:=max(deletion_end_position)

The commit on dev is 

gpcr-dev::root[/home/isrddev/chaise] git log
commit 07279e7378a815582b989c56261e73b97ec8e7fb
Merge: 91a7545 0efc574
Author: robes <robes@users.noreply.github.com>
Date:   Thu Jun 30 17:57:55 2016 -0700

    Merge pull request #486 from informatics-isi-edu/r-rs-authen

    Disable forcing login in record and recordset

commit 0efc5741512e26befab79fa5052f06f05c59fa91
Author: Jennifer Chen <jchen@isi.edu>
Date:   Thu Jun 30 14:46:31 2016 -0700

    Record app should not require login until unauthorized error

commit 33807580dc4f2a2f4de481e6879141edb6688d1d
Author: Jennifer Chen <jchen@isi.edu>
Date:   Thu Jun 30 14:11:56 2016 -0700

    recordset should only login when getting authentication error, and not require login at start.

commit 91a754510e3aa7b7efb632f966ca38033dcbf940
Merge: 50d7f9e 95be29e
Author: Josh Chudy <jchudy@isi.edu>
Date:   Thu Jun 30 14:29:10 2016 -0700

    Merge pull request #485 from informatics-isi-edu/urlParser

    Url parser

**Comment by karlcz** [comment]
@akumar03  This does not look like the same kind of error.  It is not reporting a self-link and the URL does not look like a self-link either.

This looks more like a garden variety modeling ambiguity between construct_gui and construct_deletion. However, it makes me wonder if you're running the latest ERMrest or not.  In the past few weeks, we made a patch to ERMrest that would accept this kind of ambiguity instead of raising a 409 conflict.

**Comment by carlkesselman** [comment]
Anoop.  Can you follow up and confirm.  If we are not running the latest version I am concerned about our release procedure.

Carl

Sent from my iPhone

On Jul 1, 2016, at 4:43 PM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:


@akumar03<https://github.com/akumar03> This does not look like the same kind of error. It is not reporting a self-link and the URL does not look like a self-link either.

This looks more like a garden variety modeling ambiguity between construct_gui and construct_deletion. However, it makes me wonder if you're running the latest ERMrest or not. In the past few weeks, we made a patch to ERMrest that would accept this kind of ambiguity instead of raising a 409 conflict.

-

**Comment by akumar03** [comment]
It is at the following commit, which is the last commit on ermrest: 
gpcr-dev::root[/home/isrddev/ermrest] git log
commit ff7f277a6b66746ef32fd2850a1dc45241a2d9d2
Author: Karl Czajkowski <...>
Date:   Tue Jun 28 17:58:47 2016 -0700


We have the dev-update script running regularly, but Alejandro and I suspect if it is working properly. 

I re-provisioned dev on Friday by configuring the dev-update.sh to be similar to one on synapse-dev.

**Comment by hongsudt** [comment]
@akumar03 can you check whether construct_deletion is ambiguous?

**Comment by akumar03** [comment]
All the tables were created in public shemas in addition to individual schemas. I dropped the public schema and recreated it.  We need to review the etl scripts for source of the problem.

**Comment by hongsudt** [comment]
@akumar03 Is this still a problem or can we can close this issue now?

**Comment by hongsudt** [comment]
Since nobody replied, I am going to assume this has been fixed and close the issue.
